name: Delete Archive Files

on:
  push:
    branches:
      - main

jobs:
  delete_archive_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete archive files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete all files in /archive/refs/tags/ directory
          git rm -r --ignore-unmatch /releases
          git commit -m "Delete archive files"
          git push
